matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.5"
        - "3.6"
      install:
        - pip install Flask
    - language: node_js
      node_js: 
        - "node"
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - npm i -g npm@^3
        - sleep 3
        - cd frontend
        - npm install
      install:
        - npm i --save
        - npm install iview --save
        - npm install axios --save
        - npm install he --save
        - npm install --save-dev @vue/test-utils
        - npm install flush-promises --save
        - npm install karma-chrome-launcher --save
      script:
        - npm test
